### ISSUE TITLE
App crashes after inserting the PIN

### ISSUE THREAD

**Issue by smnthermes** [nuclearfog/Shitter#8]
`FATAL EXCEPTION: AsyncTask #1
Process: org.nuclearfog.twidda, PID: 9809
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Exception.printStackTrace()' on a null object reference
	at f.a.b.b.f.doInBackground(:1)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more`

**Comment by nuclearfog** [comment]
Thanks, I have fixed it!
